### ISSUE TITLE
Check out this GSoC repo from 2019 as a possible template for tracking activity

### ISSUE THREAD

**Issue by rsignell-usgs** [fsspec/GSoC-kechunk-2022#1]
@peterm790 , Check out this [GSoC repo from 2019](https://github.com/intake/intake-gsoc-gui/issues?q=is%3Aissue) as a possible template for tracking activity.  I think it worked pretty well!

**Comment by martindurant** [comment]
Here is my video about OSS: https://anaconda.cloud/your-first-oss-contribution ; I think you need to register with the site to be able to see it.

**Comment by peterm790** [comment]
Thanks @martindurant, will have a look

**Comment by peterm790** [comment]
@rsignell-usgs I have created a markdown file (https://github.com/fsspec/GSoC-kechunk-2022/blob/main/GSOC_monitor.md) and will work towards continually updating it as we progress to hopefully produce a similar report to the awesome one done by Harman!

**Comment by rsignell-usgs** [comment]
@peterm790 , looking good!  It's a great way to track (and refresh memory on) your progress!
