### ISSUE TITLE
Add Peter to the ESIP JupyterHub on AWS

### ISSUE THREAD

**Issue by rsignell-usgs** [fsspec/GSoC-kechunk-2022#2]
The ESIP JupyterHub on AWS (https://jupyter.qhub.esipfed.org) is a great place to run workflows that analyze and visualize kerchunked data because:
* it runs on AWS in us-west-2, thus on very fast internet
* if the data being accessed is on AWS the performance is good and the data transmission (egress) costs are low for accessing requester-pays buckets. (and if the data is on AWS us-west-2, the costs are zero!
* you can easily scale up remote Dask clusters on demand to gain large data rates on chunked data
* there are conda environments already set up for this type of work

**Comment by peterm790** [comment]
Just confirming I have managed to add the AWS credentials and access some requester pays data on aws.
