### ISSUE TITLE
Update GSOC_monitor

### ISSUE THREAD

**Issue by rsignell-usgs** [fsspec/GSoC-kechunk-2022#9]
@peterm790, I've been immersed in SciPy and ESIP Summer Meeting last week and this one, and thought I'd better catch up on what you've been up to:  https://github.com/fsspec/GSoC-kechunk-2022/blob/main/GSOC_monitor.md
Got time for a quick update there?

**Comment by peterm790** [comment]
Yes forgot to update! will do so now
